title: Variable Values user documentation
email: gustavo@hipertipo.com
description: A RoboFont extension to visualize and edit values in a designspace.
baseurl: ""
url: https://gferreira.github.io/VariableValues/

markdown: kramdown

collections:
  topics:
    output: true
    permalink: /:path/
  reference:
    output: true
    permalink: /:path/

version: 0.1.0

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock

jekyll_tidy:
  exclude: []
  # ignore_env: development
  compress_html: false
